steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - gcloud
  - functions
  - deploy
  - function-1
  - --region=europe-central2
  - --source=function-1
  - --trigger-http
  - --runtime=python312
options:
 logging: CLOUD_LOGGING_ONLY
